#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    ## Ubuntu
   add-apt-repository ppa:oibaf/graphics-drivers -y
   echo "\
        software-properties-common \
        vainfo \
	      mesa-va-drivers \
	      mesa-vdpau-drivers \
      	libdrm-amdgpu1 \
	      libavutil56" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
        iptables \
        openssh \
        python3 \
        py3-pip" >> /mod-repo-packages-to-install.list
fi

echo "\
    sshuttle" >> /mod-pip-packages-to-install.list

chown -R root:root /root
chmod -R 600 /root/.ssh
